key : clean_typos
prompt : 'Fix typos, punctuation, and other mistakes in the text below. Only return the cleaned text: \n{response}'

---
key : clean_boilerplate
prompt : 'Given the following RFI response, remove any boilerplate, page numbers, headers, or salutations, closing statements,  or professional closing. Keep only the body of the message. \n{response}'

---
key : summarize_response
prompt : 'Given the following response, summarize the main ideas in two or three sentences: \n{response}.'


---
key: major_modality
prompt : Determine the following machine learning or AI modalities in sample. Return the results in a markdown list only with the name of the each modality and no description. Do not use any special punctuation. \n{response}

---
key: major_themes
prompt : Summarize the following responses into no more than five key themes. Return the results in a markdown list only with the name of the theme and no description. Do not use any special punctuation. \n{multi_response_chunk}


---
key: simplify_themes
prompt : Simplify the given te listed, getting rid of specific details. Reduce the complexity, make them simple. \n{theme}

---
key: explain_score
prompt: 'Quote the exact subset text that explains how the theme "{theme}". Only return the quote. Return an None and do not quote if there are no matching sections. This is the text:\n {response}'

---
key: group_themes
prompt : Combine and reduce the following list into no more than 12 items. Order by importance. Return the results in a bulleted list with only a descriptive name and no description. Do not use any special punctuation. \n{themes}

---
key: measure_themes
prompt : 'For the survey response "{response}" evaluate the following themes. Use 0 if the theme is not represented or there is insufficent information, or 1 if the theme is strongly represented. Only return 0, 1 for each theme. Return the results as a JSON. Do not explain the result. The themes are: \n{themes}'

---
key: describe_theme
prompt : 'Describe "{theme}" using only a few sentences. As context, use the following survey responses: {responses}'

---
key: keyword_themes
prompt : 'Using one word, restate the theme: {theme}. The description of the theme is: {desc}'

---
key: executive_summary
prompt : 'Provide a short one or two sentence executive summary of the following obervations from the survey. Only provide the executive summary and no other text. \n{all_theme_desc}'

---
key: actionable_steps
prompt : 'Provide actionable steps the organization can take to implement the following. Provide no more than three items. Return the results in a markdown list. \n{theme_description}'


---
key: emoji_themes
prompt : 'Describe "{theme}" using a single emoji. The description of the theme is: {desc}'

---
key: synthetic_responses
prompt : 'Given the "{theme}" create three or four synthetic responses to protect the identify of the respondents.  Return the results in a markdown list. Match the style and prose of the original response. As context, use the following survey responses: {responses}'

---
key: sample_responses
prompt : 'Given the "{theme}" choose three or four real responses that best match the theme.  Return the results in a markdown list. Return the exact response. As context, use the following survey responses: {responses}'
