key : summarize_response
prompt : 'Summarize the following text below into two or three sentences. Use declarative language: \n{response}'

---

key : clean_typos
prompt : 'Fix typos, punctuation, and other mistakes in the text below. Only return the cleaned text: \n{response}'

---
key : clean_boilerplate
prompt : 'Given the following RFI response, remove any boilerplate, page numbers, headers, or salutations, closing statements,  or professional closing. Keep only the body of the message. \n{response}'

---

key: major_modality
prompt : Determine modalities used in the projects. Possible answer could include text, audio, satellite, etc. Return the results in a markdown list only with the name of the each modality and no description. Do not use any special punctuation. \n{multi_response_chunk}

---
key: major_themes
prompt : Summarize the following responses into no more than five key themes. Return the results in a markdown list only with the name of the theme and no description. Do not use any special punctuation. \n{multi_response_chunk}


---
key: simplify_themes
prompt : Simplify the given te listed, getting rid of specific details. Reduce the complexity, make them simple. \n{theme}

---
key: explain_score
prompt: 'Explain how the theme "{theme}" is relevant in text below. If the text is not relevant, print None and explain why it is not relevant. This is the text:\n {response}'

---
key: group_themes_12
prompt : Combine and reduce the following list into no more than 12 items. Order by importance. Return the results in a bulleted list with only a descriptive name and no description. Do not use any special punctuation. \n{themes}

---
key: group_themes
prompt : Combine and reduce the following list. Order by importance. Return the results in a bulleted list with only a descriptive name and no description. Do not use any special punctuation. \n{themes}

---
key: measure_themes
prompt : 'For the survey response "{response}" evaluate the following themes. Use 0 if the theme is not represented or there is insufficent information, or 1 if the theme is strongly represented. Only return 0, 1 for each theme. Return the results as a JSON. Do not explain the result. The themes are: \n{themes}'

---
key: describe_dept
prompt : 'Summarize how AI is used in the projects for the Federal department {department}. Return a list. Be succinct and clear. The projects are:\n{responses}'
---
key: clean_dept_response
prompt : 'Rewrite for clarity. Avoid long sentences.\n{responses}'


---
key: describe_theme
prompt : 'Describe how AI is used in a one or two sentence executive summary. Be succinct and clear. Do not return a list. The projects are:\n{responses}'

---
key: keyword_themes
prompt : 'Using one word, restate the theme: {theme}. The description of the theme is: {desc}'

---
key: executive_summary
prompt : 'Provide a short one or two sentence executive summary of the following observations from the survey. Only provide the executive summary and no other text. Describe how they all interrelate. \n{all_theme_desc}'

---
key: actionable_steps
prompt : 'Provide actionable steps the organization can take to implement the following. Provide no more than three items. Return the results in a markdown list. \n{theme_description}'


---
key: emoji_themes
prompt : 'Describe "{theme}" using a single emoji. The description of the theme is: {desc}'

---
key: synthetic_responses
prompt : 'Given the "{theme}" create three or four synthetic responses to protect the identify of the respondents.  Return the results in a markdown list. Match the style and prose of the original response. As context, use the following survey responses: {responses}'

---
key: sample_responses
prompt : 'Given the "{theme}" choose three or four real responses that best match the theme.  Return the results in a markdown list. Return the exact response. As context, use the following survey responses: {responses}'
